"""Fuentes (repo/sesión), descubrimiento y correcciones."""

from .base import _Frozen


class RepositorySourceSummary(_Frozen):
    source_id: str
    name: str
    type: str
    origin: str
    trust: str
    status: str
    quality: int
    quality_label: str
    updated_at: str


class SourceObservation(_Frozen):
    date: str
    text: str


class RepositorySource(_Frozen):
    """Full catalog ficha of a permanent repository source (V3.6.x Source Catalog)."""

    source_id: str
    name: str
    type: str
    origin: str
    trust: str
    status: str
    quality: int
    quality_label: str
    updated_at: str
    # automatic (computed by OSAP)
    representations: int
    works: int
    composers: int
    formats: list[str] = []
    catalogues: list[str] = []
    duplicate_percent: float = 0.0
    coverage: list[str] = []
    capabilities: list[str] = []
    # documentation (written by a human)
    description: str = ""
    license: str = ""
    website: str = ""
    contact: str = ""
    notes: str = ""
    observations: tuple[SourceObservation, ...] = ()
    # community (generated by users)
    tags: list[str] = []
    community_rating: int = 0
    reviews: int = 0
    searches: int = 0
    downloads: int = 0
    contributions: int = 0
    availability: float = 0.0


class ErrorBody(_Frozen):
    code: str
    message: str
    details: dict[str, object] = {}


class SessionSource(_Frozen):
    """A user's temporary source (Session Instance), used during a search/session."""

    source_id: str
    name: str
    type: str
    location: str
    status: str
    analysis: dict[str, object] = {}
    created_at: str


class DiscoverSource(_Frozen):
    """A suggested source from the discovery catalog."""

    source_id: str
    name: str
    type: str
    origin: str
    trust: str
    quality: int
    url: str = ""


class SessionSourceCreate(_Frozen):
    name: str
    type: str
    location: str = ""


class SourcePreviewRequest(_Frozen):
    url: str
    name: str = ""


class SourcePreviewResponse(_Frozen):
    ok: bool
    fields: list[str] = []
    error: str | None = None


class SourceSuggestionRequest(_Frozen):
    name: str
    type: str
    location: str
    mapping: dict[str, object] = {}


class SourceSuggestionRead(_Frozen):
    id: str
    name: str
    type: str
    location: str
    mapping: dict[str, object]
    requested_by: str
    status: str
    admin_message: str | None = None
    created_at: str


class SourceSuggestionResolveRequest(_Frozen):
    action: str
    message: str = ""


class CorrectionRequest(_Frozen):
    """Solicitud de contacto o de corrección de datos del catálogo (OSAP).

    `kind`: contact | source | composer | work.
    Para `work` (título de obra OMR) se usa `entity_provider="omr"` y `field="title"`.
    """

    kind: str
    entity_id: str | None = None
    entity_provider: str | None = None
    field: str | None = None
    current_value: str | None = None
    proposed_value: str | None = None
    message: str = ""
    contact_email: str | None = None


class CorrectionRead(_Frozen):
    id: str
    kind: str
    entity_id: str | None = None
    entity_provider: str | None = None
    field: str | None = None
    current_value: str | None = None
    proposed_value: str | None = None
    message: str = ""
    contact_email: str | None = None
    requested_by: str | None = None
    requested_by_name: str | None = None
    requested_by_email: str | None = None
    status: str
    admin_message: str | None = None
    created_at: str


class CorrectionResolveRequest(_Frozen):
    action: str
    message: str = ""


