"""Generic provider adapter: paquete (F5.3)."""

from .adapter import GenericProviderAdapter, ProviderFetcher
from .loader import (
    _auth_type,
    _flatten_work_mapping,
    _load_definition_dir,
    _load_definition_file,
    _load_transforms,
    _normalize_transforms,
    _parse_endpoints,
    _split_work_mapping,
    load_definition,
    load_definition_from_config,
)
from .mapping import (
    _apply_mapping,
    _apply_transform,
    _as_opt_bool,
    _as_opt_float,
    _as_opt_int,
    _as_opt_str,
    _as_strings,
    _build_metadata,
    _build_resource,
    _first_list,
    _get_path,
    _resolve_query,
    _resolve_url,
    _strip_parenthetical,
)
from .models import Endpoint, ProviderDefinition, ProviderHttpClient, ProviderQuery

__all__ = [
    'Endpoint',
    'GenericProviderAdapter',
    'ProviderDefinition',
    'ProviderFetcher',
    'ProviderHttpClient',
    'ProviderQuery',
    '_apply_mapping',
    '_apply_transform',
    '_as_opt_bool',
    '_as_opt_float',
    '_as_opt_int',
    '_as_opt_str',
    '_as_strings',
    '_auth_type',
    '_build_metadata',
    '_build_resource',
    '_first_list',
    '_flatten_work_mapping',
    '_get_path',
    '_load_definition_dir',
    '_load_definition_file',
    '_load_transforms',
    '_normalize_transforms',
    '_parse_endpoints',
    '_resolve_query',
    '_resolve_url',
    '_split_work_mapping',
    '_strip_parenthetical',
    'load_definition',
    'load_definition_from_config',
]
