"""Generic Provider Adapter (Provider API v1.3) — facade.

F5.3: la implementación vive en `src/osap/infrastructure/providers/adapters/generic/`.
"""

from __future__ import annotations

from src.osap.infrastructure.providers.adapters.generic import (
    Endpoint,
    GenericProviderAdapter,
    ProviderDefinition,
    ProviderFetcher,
    ProviderHttpClient,
    ProviderQuery,
    _apply_mapping,
    _apply_transform,
    _as_opt_bool,
    _as_opt_float,
    _as_opt_int,
    _as_opt_str,
    _as_strings,
    _auth_type,
    _build_metadata,
    _build_resource,
    _first_list,
    _flatten_work_mapping,
    _get_path,
    _load_definition_dir,
    _load_definition_file,
    _load_transforms,
    _normalize_transforms,
    _parse_endpoints,
    _resolve_query,
    _resolve_url,
    _split_work_mapping,
    _strip_parenthetical,
    load_definition,
    load_definition_from_config,
)

__all__ = [
    'Endpoint',
    'GenericProviderAdapter',
    'ProviderDefinition',
    'ProviderFetcher',
    'ProviderHttpClient',
    'ProviderQuery',
    '_apply_mapping',
    '_apply_transform',
    '_as_opt_bool',
    '_as_opt_float',
    '_as_opt_int',
    '_as_opt_str',
    '_as_strings',
    '_auth_type',
    '_build_metadata',
    '_build_resource',
    '_first_list',
    '_flatten_work_mapping',
    '_get_path',
    '_load_definition_dir',
    '_load_definition_file',
    '_load_transforms',
    '_normalize_transforms',
    '_parse_endpoints',
    '_resolve_query',
    '_resolve_url',
    '_split_work_mapping',
    '_strip_parenthetical',
    'load_definition',
    'load_definition_from_config',
]
