"""V3.1 — OSAP Platform API public contract (DTOs).

These are the *public* contract of the REST API. They are independent of the domain
model: they never reuse internal domain Value Objects, so a change to, e.g.,
`WorkDescriptor` cannot break `SearchResponse`. They are immutable (frozen) and typed.
FastAPI only serializes/validates them; they do not depend on the domain.
"""

from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict

T = TypeVar("T")


class _Frozen(BaseModel):
    model_config = ConfigDict(frozen=True)


class SearchRequest(_Frozen):
    model_config = ConfigDict(
        frozen=True,
        json_schema_extra={
            "examples": [
                {"query": "Ave Verum KV 618", "limit": 10},
                {"query": "Mozart", "composer": "Mozart", "limit": 20},
            ]
        },
    )
    query: str = ""
    limit: int = 10
    page: int = 1
    composer: str | None = None
    title: str | None = None
    catalogue: str | None = None
    instrumentation: str | None = None
    language: str | None = None


class WorkInfo(_Frozen):
    work_id: str
    title: str
    composer: str | None = None
    catalogue: str | None = None


class RepresentationInfo(_Frozen):
    id: str
    provider: str
    format: str
    confidence: float = 0.0
    url: str | None = None  # never exposed: the client only uses `id`
    title: str | None = None


class EvidenceInfo(_Frozen):
    source: str
    code: str
    score: float = 0.0


class WorkRelationships(_Frozen):
    aliases: list[str] = []
    related_catalogues: list[str] = []
    editions: list[str] = []
    parent_work: str | None = None
    movements: list[str] = []


class SearchResultItem(_Frozen):
    work: WorkInfo
    representation: RepresentationInfo
    representations: list[RepresentationInfo] = []
    score: float
    evidence: list[EvidenceInfo] = []
    relationships: WorkRelationships | None = None


class SearchResponse(_Frozen):
    search_id: str
    results: list[SearchResultItem] = []
    total: int = 0
    page: int = 1
    per_page: int = 10


class JobCreateRequest(_Frozen):
    model_config = ConfigDict(
        frozen=True,
        json_schema_extra={"examples": [{"type": "provider-sync"}]},
    )
    type: str


class JobResponse(_Frozen):
    job_id: str
    type: str
    state: str
    progress: int = 0
    result: dict[str, object] = {}


class ProviderResponse(_Frozen):
    provider_id: str
    name: str
    available: bool
    formats: list[str] = []
    last_sync: str | None = None


class KnowledgeObservationDTO(_Frozen):
    execution_id: str
    source: str
    field: str
    value: str
    provider: str | None = None


class KnowledgeFactDTO(_Frozen):
    fact_type: str
    field: str
    value: str
    count: int


class KnowledgeSuggestionDTO(_Frozen):
    suggestion_type: str
    field: str
    source_value: str
    target_value: str
    reason: str


class KnowledgeResponse(_Frozen):
    observations: list[KnowledgeObservationDTO] = []
    facts: list[KnowledgeFactDTO] = []
    suggestions: list[KnowledgeSuggestionDTO] = []


class SystemHealthResponse(_Frozen):
    status: str


class SystemVersionResponse(_Frozen):
    version: str


class SystemStatisticsResponse(_Frozen):
    providers: int
    searches: int
    jobs: int
    knowledge_observations: int
    knowledge_facts: int
    knowledge_suggestions: int


class RepositorySourceSummary(_Frozen):
    source_id: str
    name: str
    type: str
    origin: str
    trust: str
    status: str
    quality: int
    quality_label: str
    updated_at: str


class SourceObservation(_Frozen):
    date: str
    text: str


class RepositorySource(_Frozen):
    """Full catalog ficha of a permanent repository source (V3.6.x Source Catalog)."""

    source_id: str
    name: str
    type: str
    origin: str
    trust: str
    status: str
    quality: int
    quality_label: str
    updated_at: str
    # automatic (computed by OSAP)
    representations: int
    works: int
    composers: int
    formats: list[str] = []
    catalogues: list[str] = []
    duplicate_percent: float = 0.0
    coverage: list[str] = []
    capabilities: list[str] = []
    # documentation (written by a human)
    description: str = ""
    license: str = ""
    website: str = ""
    contact: str = ""
    notes: str = ""
    observations: tuple[SourceObservation, ...] = ()
    # community (generated by users)
    tags: list[str] = []
    community_rating: int = 0
    reviews: int = 0
    searches: int = 0
    downloads: int = 0
    contributions: int = 0
    availability: float = 0.0


class ErrorBody(_Frozen):
    code: str
    message: str
    details: dict[str, object] = {}


class SessionSource(_Frozen):
    """A user's temporary source (Session Instance), used during a search/session."""

    source_id: str
    name: str
    type: str
    location: str
    status: str
    analysis: dict[str, object] = {}
    created_at: str


class DiscoverSource(_Frozen):
    """A suggested source from the discovery catalog."""

    source_id: str
    name: str
    type: str
    origin: str
    trust: str
    quality: int
    url: str = ""


class SessionSourceCreate(_Frozen):
    name: str
    type: str
    location: str = ""


class SearchModelCriteria(_Frozen):
    key: str
    label: str


class SearchModelBlock(_Frozen):
    id: str
    label: str
    kind: str  # "text" | "multi" | "range" | "boolean"
    criteria: list[SearchModelCriteria] = []
    options: list[str] = []


class SearchModel(_Frozen):
    blocks: list[SearchModelBlock] = []


class IntentResponse(_Frozen):
    type: str  # composer | work | catalogue | collection | source
    label: str


# --- votes & statistics (v1) -----------------------------------------------


class VoteRequest(_Frozen):
    model_config = ConfigDict(
        frozen=True,
        json_schema_extra={"examples": [{"vote": 5}]},
    )
    vote: int


class VoteResponse(_Frozen):
    work_id: str
    vote: int
    voted_at: str
    vote_day: str


class WorkStatisticsResponse(_Frozen):
    work_id: str
    vote_count: int
    vote_average: float | None


class ComposerStatisticsResponse(_Frozen):
    composer_id: str
    vote_count: int
    vote_average: float | None


class VotesOverviewResponse(_Frozen):
    total_votes: int
    top_works: list[WorkStatisticsResponse] = []
    top_composers: list[ComposerStatisticsResponse] = []
    last_execution: dict[str, object] | None = None


class SuccessEnvelope(_Frozen, Generic[T]):  # noqa: UP046
    success: bool
    request_id: str
    data: T


class ErrorEnvelope(_Frozen):
    success: bool
    request_id: str
    error: ErrorBody
